### ISSUE TITLE
Bug - test configuration in backend not working anymore

### ISSUE THREAD

**Issue by rakibabu** [justbetter/magento2-sentry#32]
The button test configuration in the backend of Magento is not working anymore.

**Comment by DominicWatts** [comment]
On 2.3.1 I get error pointing towards `Zend\Diactoros\ResponseFactory`

I think composer has all required packages. I will check again tonight but this still appears to be issue even with latest merges?

**Comment by rakibabu** [comment]
In Released 2.1.0 this issue is fixed. Thanks to @JeroenBoersma @DominicWatts  :) I'll investigate this issue for 2.3.1.

**Comment by DominicWatts** [comment]
Was missing nyholm/psr7

FYI if anyone else makes same mistake the error is this

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Zend\Diactoros\ResponseFactory::__construct(), 0 passed in /var/www/magento/vendor/php-http/discovery/src/ClassDiscovery.php on line 203 and at least 1 expected in /var/www/magento/generated/code/Zend/Diactoros/ResponseFactory.php:29 
Stack trace: 
#0 /var/www/magento/vendor/php-http/discovery/src/ClassDiscovery.php(203): Zend\Diactoros\ResponseFactory->__construct() 
#1 /var/www/magento/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php(58): Http\Discovery\ClassDiscovery::instantiateClass('Zend\\Diactoros\\...') 
#2 /var/www/magento/vendor/php-http/curl-client/src/Client.php(84): Http\Discovery\Psr17FactoryDiscovery::findResponseFactory() 
#3 /var/www/magento/vendor/php-http/discovery/src/ClassDiscovery.php(203): Http\Client\Curl\Client->__construct() 
#4 /var/www/magento/vendor/php-http/discovery/src/HttpAsyncClientDiscovery.php(34): Http\Discovery\ClassDiscovery::instantiateClass('Http\\Client\\Cur...') 
#5 /var/www/magento/vendor/sentry/sentry/src/C in /var/www/magento/generated/code/Zend/Diactoros/ResponseFactory.php on line 29
```

So all good

**Comment by rakibabu** [comment]
Good to hear. I'm closing this issue.
